ledger/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static
from .views import RecipeListView, RecipeDetailView, RecipeCreateView, RecipeImageAddView, IngredientAddView

urlpatterns = [
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name = "recipe"),
    path('recipe/<int:pk>/add_image/', RecipeImageAddView.as_view(), name = 'add_image'),
    path('recipes/list/', RecipeListView.as_view(), name = "recipes/list"),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('recipe/add/', RecipeCreateView.as_view(), name = 'add'),
    path('new_ingredient/', IngredientAddView.as_view(), name = 'ingredient'),
]

app_name = "ledger"
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

ledger/models.py
"""This file contains the models for the recipebook."""
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length = 50)
    bio = models.CharField(max_length = 255)

class Ingredient(models.Model):
    """Model for a single ingredient."""
    name = models.CharField(max_length = 255)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ingredients', args[str(self.name)])

class Recipe(models.Model):
    """Model for a recipe."""
    name = models.CharField(max_length = 255, null = True)
    author = models.CharField(max_length = 50, null = True)
    created_on = models.DateTimeField(auto_now_add = True)
    updated_on = models.DateTimeField(auto_now = True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ledger:recipe', args=[self.pk])

class RecipeIngredient(models.Model):
    """Model for an ingredient in a recipe."""
    quantity = models.CharField(max_length = 255)
    ingredient = models.ForeignKey(Ingredient, on_delete = models.CASCADE, related_name = "recipe")
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE, related_name = "ingredients")

class RecipeImage(models.Model):
    image = models.ImageField(upload_to = "images/", null = False)
    description = models.CharField(max_length = 255, null = True)
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE, related_name = "image")

ledger/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory
from .models import Recipe, RecipeIngredient, RecipeImage, Ingredient

class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']

class RecipeImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        fields = ['image', 'description']

class IngredientCreateForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']

IngredientFormSet = inlineformset_factory(
    Recipe, RecipeIngredient,
    fields = '__all__',
    extra = 1, can_delete = False
)

RecipeImageFormSet = modelformset_factory(
    RecipeImage, form = RecipeImageForm,
    extra = 1, can_delete = False
)

IngredientCreateFormSet = modelformset_factory(
    Ingredient, form = IngredientCreateForm,
    extra = 1, can_delete = False
)

ledger/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Recipe, RecipeImage, Ingredient
from .forms import RecipeCreateForm, RecipeImageForm, IngredientFormSet, RecipeImageFormSet, IngredientCreateForm, IngredientCreateFormSet

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipeList.html'
    redirect_field_name = 'accounts/login'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipe.html'
    redirect_field_name = 'accounts/login'

class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeCreateForm
    template_name = 'recipeCreate.html'
    redirect_field_name = 'accounts/login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = IngredientFormSet(self.request.POST)
        else:
            context['formset'] = IngredientFormSet()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user.username
        context = self.get_context_data()
        formset = context['formset']

        if formset.is_valid():
            self.object = form.save()
            ingredients = formset.save(commit = False)
            
            for ingredient in ingredients:
                ingredient.recipe = self.object
                ingredient.save()
            return redirect(self.get_success_url())
        return self.form_invalid(form)

class RecipeImageAddView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeImageForm 
    template_name = 'recipeImage.html'
    redirect_field_name = 'accounts/login'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['image_formset'] = RecipeImageFormSet(self.request.POST, self.request.FILES,
                                                            queryset = RecipeImage.objects.none())
        else:
            context['image_formset'] = RecipeImageFormSet(queryset = RecipeImage.objects.none())
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        image_formset = context['image_formset']

        if image_formset.is_valid():
            recipe = get_object_or_404(Recipe, pk=self.kwargs.get('pk'))

            for image_form in image_formset:
                if image_form.cleaned_data:
                    image = image_form.save(commit = False)
                    image.recipe = recipe
                    image.save()

            return redirect(recipe.get_absolute_url())
        return self.form_invalid(form)

    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        for field in form.fields.values():
            field.required = False
        return form 

class IngredientAddView(LoginRequiredMixin, CreateView):
    model = Ingredient
    form_class = IngredientCreateForm
    template_name = 'ingredientCreate.html'
    redirect_field_name = 'accounts/login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = IngredientCreateFormSet(self.request.POST, queryset = Ingredient.objects.none())
        else:
            context['formset'] = IngredientCreateFormSet(queryset = Ingredient.objects.none())
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']

        if formset.is_valid():
            formset.save()
            return redirect(reverse("ledger:recipes/list"))
        return self.form_invalid(form)

    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        for field in form.fields.values():
            field.required = False
        return form

ledger/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <Title>{% block title %} {% endblock %} </Title>
    </head>
    <body>
        <h1>Recipe Book</h1>
        <h2>{{ object.name }}</h2>
        {% block content %}
        {% endblock %}
        {% url 'ledger:recipe' as recipe %}
        {% url 'ledger:recipes/list' as recipelist %}
        {% if user.is_authenticated and request.path == recipe or request.path == recipelist %}
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Logout</button>
            </form>
            {% else %}
                <a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        {% endif %}
    </body>
</html>

ledger/templates/ingredientCreate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Book{% endblock %}
{% block content %}
    <form method= "post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_p }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

    <p></p>

    <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

ledger/templates/recipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Book{% endblock %}
{% block content %}
    <h2>
        By {{ recipe.author }}
    </h2>
    <ul>
        {% for image in object.image.all %}
        {% if image %}
            <img src="{{ image.image.url }}" alt="image.description">
        {% endif %}
        {% endfor %}
        {% for ingredient in object.ingredients.all %}
            <li>{{ ingredient.ingredient.name }}{{ ": " }}{{ ingredient.quantity }}</li>
        {% endfor %}
    </ul>
{% endblock %}

ledger/templates/recipeCreate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Book{% endblock %}
{% block content %}
    <form method= "post" enctype = "multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <h3>Ingredients</h3>
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_p }}
        {% endfor %}
        {{ image_formset.management_form }}
        {% for image_form in image_formset %}
            {{ image_form.as_p }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

    <p></p>

    <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

ledger/templates/recipeImage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Book{% endblock %}
{% block content %}
    <form method= "post" enctype = "multipart/form-data">
        {% csrf_token %}
        <h3>Add Image</h3>
        {{ image_formset.management_form }}
        {% for image_form in image_formset %}
            {{ image_form.as_p }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

    <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

ledger/templates/recipeList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Book{% endblock %}
{% block content %}
    <ul>
        {% for recipe in object_list %}
            <li><a href="{{ recipe.get_absolute_url }}">{{recipe.name}}</a></li>
        {% endfor %}
    </ul>
    <a href = "{% url 'ledger:add' %}">Add a recipe!</a>
    <p></p>
    <a href = "{% url 'ledger:ingredient' %}">Add a new ingredient!</a>
{% endblock %}